### ISSUE TITLE
API KEY 

### ISSUE THREAD

**Issue by abduljeleelng** [PacktPublishing/Full-Stack-React-Projects#15]
Thank for the beautiful information provided and the guides, However, as you explain in your book about the authorization and authentication for the access some routes. and during our coding, I notice we set a time limit for the token (JWT token). However, how can I set up an API key for the user to access some route instead of login and generate the token? 

For Instance, I have a pubic route and want to Identify each user making a request to that routes base on user ID and API key. Note, API key can not be expired as a token except the user make a change. 

I will be so grateful, for any hint or snippet.

Thank you all

**Comment by shamahoque** [comment]
A bit late to this query, but here goes for anyone else considering something similar:

The JWT Authentication example discussed in this book covers user authentication which works with tokens that are generated per logged-in session and can be discarded after the session. But for an Api Key type implementation where the tokens need to persist, there are more considerations to be made. You could possible apply the same JWT signing and verification mechanisms but the API keys would need to be generated and stored as well.

**Comment by abduljeleelng** [comment]
Thank you so much for your contribution.
I really appreciate your help, however, I later used this approach ```https://github.com/abduljeleelng/apikey``` 
But I am still looking for ways for improvement.
Thank so much

**Comment by shamahoque** [comment]
Looks like you are doing the part of storing the API key in the database with each user. 
I think this works fine for the use case you described, where you want to identify the user making the public API request.

If the API key usage needs to be restricted somehow, then adding the JWT auth mechanisms would become relevant.

**Comment by abduljeleelng** [comment]
Thank you so much, 
I really appreciate your time and advice
