### ISSUE TITLE
Unable to launch demo app - Thanks

### ISSUE THREAD

**Issue by gokulakrishna9** [PacktPublishing/Full-Stack-React-Projects#2]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\########\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'development' ]
2 info using npm@6.1.0
3 info using node@v8.10.0
4 verbose run-script [ 'predevelopment', 'development', 'postdevelopment' ]
5 info lifecycle mern-simplesetup@1.0.0~predevelopment: mern-simplesetup@1.0.0
6 info lifecycle mern-simplesetup@1.0.0~development: mern-simplesetup@1.0.0
7 verbose lifecycle mern-simplesetup@1.0.0~development: unsafe-perm in lifecycle true
8 verbose lifecycle mern-simplesetup@1.0.0~development: PATH: #####
9 verbose lifecycle mern-simplesetup@1.0.0~development: CWD: C:\Users\########\########\full-stack-react\ex\ch1\mern-simplesetup
10 silly lifecycle mern-simplesetup@1.0.0~development: Args: [ '/d /s /c', 'nodemon' ]
11 silly lifecycle mern-simplesetup@1.0.0~development: Returned: code: 1  signal: null
12 info lifecycle mern-simplesetup@1.0.0~development: Failed to exec development script
13 verbose stack Error: mern-simplesetup@1.0.0 development: `nodemon`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\########\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\########\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid mern-simplesetup@1.0.0
15 verbose cwd C:\Users\########\########\full-stack-react\ex\ch1\mern-simplesetup
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\########\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "development"
18 verbose node v8.10.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error mern-simplesetup@1.0.0 development: `nodemon`
22 error Exit status 1
23 error Failed at the mern-simplesetup@1.0.0 development script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

I keep getting this error when I try to run command: npm run development. I am running this on Windows 10.

Thanks & Regards
Gokul.

**Comment by jhorgint** [comment]
I have downloaded the simplest setup at [repository ](github.com/shamahoque/mern-simplesetup)
but when I tried npm star I got an error that is simple to fix
in package.json change this line:
`"start": "NODE_ENV=production node ./dist/server.generated.js"`
with this line
`"start": "SET NODE_ENV=production & nodemon ./dist/server.generated.js"`

**Comment by jhorgint** [comment]
I have downloaded the simplest setup at [book page 94 ](github.com/shamahoque/mern-simplesetup)
When I tried _**npm star**_ I got an error that is simple to fix
in package.json you change this line:
`"start": "NODE_ENV=production node ./dist/server.generated.js"`
with this:
`"start": "SET NODE_ENV=production & nodemon ./dist/server.generated.js"`
